name: Testing on push

on: push

jobs:
  test:
    name: Test passes
    runs-on: ubuntu-latest
    env:
      SUPABASE_URL: ${{ secrets['SUPABASE_URL'] }}
      SUPABASE_KEY: ${{ secrets['SUPABASE_KEY'] }}

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install modules
        run: npm ci

      - name: Debug Environment Variables
        run: |
          echo "SUPABASE_URL: $SUPABASE_URL"
          echo "SUPABASE_KEY: $SUPABASE_KEY"

      - name: Testing
        run: npm test
